### ISSUE TITLE
read functions unable to process NAs

### ISSUE THREAD

**Issue by SawyerRSmith** [bailey-lab/miplicorn#19]
Trying to read in MIPTools AA tables both individually using miplicorn::read_tbl_references() etc. and miplicorn::read_tbl_ref_alt_cov() and getting the following error when running both. I would like to be able to read all three tables into the function and have them reformatted in the output as previously done in the past miplicorn::read() function.

Error: Error: Names repair functions can't return `NA` values.

Original input: 
data<-miplicorn::read_tbl_ref_alt_cov(
  "~/R/extended-haplotype-Uganda/data/hap3files/DR2_reference_AA_table_hap3.csv",
  "~/R/extended-haplotype-Uganda/data/hap3files/DR2_alternate_AA_table_hap3.csv",
  "~/R/extended-haplotype-Uganda/data/hap3files/DR2_coverage_AA_table_hap3.csv"
)

and individually

 ref<-miplicorn::read_tbl_reference("~/R/extended-haplotype-Uganda/data/hap3files/DR2_reference_AA_table_hap3.csv")

Thank you!

**Comment by arisp99** [comment]
Thanks for the bug report! This error has been resolved in https://github.com/r-lib/vroom/issues/381. Please update `{vroom}` to version 1.5.6 (or greater) to fix this on your machine.

```r
# Check package version
packageVersion("vroom")

# Install the latest version 
# (you may need to build the package from source)
install.packages("vroom")
```
