### ISSUE TITLE
Keeping sample format from tables generated by MIPTools

### ISSUE THREAD

**Issue by SawyerRSmith** [bailey-lab/miplicorn#20]
Miplicorn read functions are great! I just need the function to read in the table without making the sample names all lowercase and changing dashes to underscores. This saves me time from changing all the metadata files, etc.  

Thanks! 

Example of what happens: 
ji_05_59_ug_sur_2020_1

What I need to keep them as:
JI-05-59-ug-sur-2020-01

**Comment by arisp99** [comment]
Thanks for the bug report! The sample IDs are no longer manipulated by the `read_tbl_*()` family of functions.
