### ISSUE TITLE
Filtering functions

### ISSUE THREAD

**Issue by arisp99** [bailey-lab/miplicorn#21]
### Related Problem
In many situations, it becomes helpful, if not necessary, to filter data before conducting analyses or creating figures. There are several filtering steps that we could take, but some are used almost every time.  For instance, to filter based on coverage we use the following:

``` r
library(miplicorn)
library(dplyr)

ref_file <- miplicorn_example("reference_AA_table.csv")
alt_file <- miplicorn_example("alternate_AA_table.csv")
cov_file <- miplicorn_example("coverage_AA_table.csv")

table <- read_tbl_ref_alt_cov(ref_file, alt_file, cov_file)

dplyr::filter(table, coverage > 3)
#> # A tibble: 3,847 × 10
#>    sample     gene_id       gene  mutation_name  exonic_func  aa_change targeted
#>    <chr>      <chr>         <chr> <chr>          <chr>        <chr>     <chr>   
#>  1 D10-JJJ-23 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  2 D10-JJJ-43 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  3 D10-JJJ-55 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  4 D10-JJJ-15 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  5 D10-JJJ-28 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  6 D10-JJJ-52 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  7 D10-JJJ-13 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  8 D10-JJJ-1  PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  9 D10-JJJ-45 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#> 10 D10-JJJ-38 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#> # … with 3,837 more rows, and 3 more variables: ref_umi_count <dbl>,
#> #   alt_umi_count <dbl>, coverage <dbl>
```

<sup>Created on 2021-11-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### Solution Requested
Currently, we must use `dplyr::filter()` to conduct these filtering steps. It may be beneficial to users to have a family of functions for filtering. These functions will likely just call `dplyr::filter()` under the hood, but if we specify individual functions, it may make it clearer which steps users should consider in the first place. The following, for instance, makes it explicit that the user is filtering based on the coverage.

```r
filter_coverage(table, 3)
#> # A tibble: 3,847 × 10
#>    sample     gene_id       gene  mutation_name  exonic_func  aa_change targeted
#>    <chr>      <chr>         <chr> <chr>          <chr>        <chr>     <chr>   
#>  1 D10-JJJ-23 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  2 D10-JJJ-43 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  3 D10-JJJ-55 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  4 D10-JJJ-15 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  5 D10-JJJ-28 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  6 D10-JJJ-52 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  7 D10-JJJ-13 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  8 D10-JJJ-1  PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#>  9 D10-JJJ-45 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#> 10 D10-JJJ-38 PF3D7_0106300 atp6  atp6-Ala623Glu missense_va… Ala623Glu Yes     
#> # … with 3,837 more rows, and 3 more variables: ref_umi_count <dbl>,
#> #   alt_umi_count <dbl>, coverage <dbl>
```

### Useful Filtering Functions
- [ ] `filter_coverage()`
- [ ] `filter_umi_count()`

**Comment by djgies** [comment]
Sorry I missed this earlier Aris. For the purposes of reporting mutation prevalences, which is going to be most users first stop with this, we need to have both layers of filtering, so we can filter cov and umi_count in their separate tibbles, but then merge and drop rows where either cov or umi_count is missing. I really like the way this looks though.

**Comment by arisp99** [comment]
Yes, we will need to filter on multiple conditions to report mutation prevalences. This is actually the main drawback I see to writing a family of functions like this—in many cases, it is more valuable to filter on multiple conditions at once. The power of `dplyr::filter()` is the ability to specify multiple filtering conditions at once and join them with `&` or `|`. While I do envision some scenarios where filtering just on one condition is valuable, I wonder if it's really worth coding it up, especially because when you do need to filter on multiple conditions, this would complicate the process. In the example you mentioned, you now need to figure out the order of filtering steps to conduct. Do you want to filter on `coverage` and then `umi_count` or the other way around?

Ultimately I see arguments for both having and not having this family of functions. On the one hand, these functions may make it easier for newer users to conceptually understand the steps being conducted in the analysis. However, on the other hand, as these functions will not be particularly useful for more advanced analyses, and instead `dplyr::filter()` should be used, one could argue that including these "shortcut" functions will confuse users trying to conduct complex analyses because these functions will not be useful. At the end of the day, these functions will just enforce that you are filtering on one condition and feed your data and arguments to `dplyr::filter()`. 

One solution to this would be to include the functions, which may provide benefits to less experienced users, but then include a warning in the documentation that for more complex analyses we recommend the use `dplyr::filter()` which allows for more sophisticated data filtering.
