### ISSUE TITLE
Formating error for "mutation_name" in AN tables 

### ISSUE THREAD

**Issue by SawyerRSmith** [bailey-lab/miplicorn#22]
When reading in AN tables the "mutation_name" object is incorrectly adding a,'.' between ":.:", instead of a single colon, ":".

Example
chr11:637436:.:T:A (what occurs)
chr11:637436:T:A (what should occur)

Thanks!

**Comment by arisp99** [comment]
I suspect that this is an issue with the file being read in and not `{miplicorn}`. The actual `mutation_name` variables should not be manipulated by reading in the tables.

Can you provide a [reproducible example (reprex)](https://reprex.tidyverse.org/index.html)? It is hard for me to tell the source of the issue without being able to reproduce it.

**Comment by arisp99** [comment]
Closing this issue as it was determined that `{miplicorn}` is not at fault for this misformatting.
